[jobs.test]
command = ["cargo", "test", "--features", "integration-tests"]
need_stdout = true

[jobs.clippy-all]
command = ["cargo", "clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]